### ISSUE TITLE
[BUG] aiohttp deflate error

### ISSUE THREAD

**Issue by bouwew** [plugwise/python-plugwise#23]
**Describe the bug**
Error when adding the integration for the Stretch.

**Evidence**
``` 
2020-08-21 23:20:18 ERROR (MainThread) [custom_components.plugwise.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/plugwise/config_flow.py", line 130, in async_step_user
    api = await validate_input(self.hass, user_input)
  File "/config/custom_components/plugwise/config_flow.py", line 74, in validate_input
    await api.connect()
  File "/usr/local/lib/python3.8/site-packages/Plugwise_Smile/Smile.py", line 161, in connect
    result = await resp.text()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1009, in text
    await self.read()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 973, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 358, in read
    block = await self.readany()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 380, in readany
    await self._wait('readany')
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 296, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: deflate'
```

**Home Assistant Core (please complete the following information):**
 - Version: 0.114.3
 - Deployment: hassio
 - Installed plugwise version: plugwise-beta pre-v0.7.0a0 code
 - Installed through: HACS

**Smile (please complete the following information):**
 - Sort of Smile: Stretch v2
 - Firmware: 2.3.12

**Additional context**
Adding this: `headers = {'Accept-Encoding': 'gzip'}` make the error go away.

**Comment by bouwew** [comment]
After HA Core has been upgraded to aiohttp v3.7.2 the error is gone but the integration still doesn't work.
There is no error-information that points to aiohttp, only a plugwise-timeout error is shown.

Therefore the temporary work-around has been made a permanent addition to the plugwise-code.
